open Release_config_values

val bool : value -> [`Invalid of string | `Valid]
val int : value -> [`Invalid of string | `Valid]
val float : value -> [`Invalid of string | `Valid]
val string : value -> [`Invalid of string | `Valid]
val regexp : value -> [`Invalid of string | `Valid]
val bool_list : value -> [`Invalid of string | `Valid]
val int_list : value -> [`Invalid of string | `Valid]
val float_list : value -> [`Invalid of string | `Valid]
val string_list : value -> [`Invalid of string | `Valid]
val int_in_range : int * int -> value -> [`Invalid of string | `Valid]
val int_greater_than : int -> value -> [`Invalid of string | `Valid]
val int_less_than : int -> value -> [`Invalid of string | `Valid]
val float_in_range : float * float -> value -> [`Invalid of string | `Valid]
val float_greater_than : float -> value -> [`Invalid of string | `Valid]
val float_less_than : float -> value -> [`Invalid of string | `Valid]
val string_matching : string -> value -> [`Invalid of string | `Valid]
val int_in : int list -> value -> [`Invalid of string | `Valid]
val string_in : string list -> value -> [`Invalid of string | `Valid]
val existing_file : value -> [`Invalid of string | `Valid]
val nonempty_file : value -> [`Invalid of string | `Valid]
val file_with_mode : Unix.file_perm -> value -> [`Invalid of string | `Valid]
val file_with_owner : string -> value -> [`Invalid of string | `Valid]
val file_with_group : string -> value -> [`Invalid of string | `Valid]
val existing_directory : value -> [`Invalid of string | `Valid]
val existing_dirname : value -> [`Invalid of string | `Valid]
val block_device : value -> [`Invalid of string | `Valid]
val character_device : value -> [`Invalid of string | `Valid]
val symbolic_link : value -> [`Invalid of string | `Valid]
val named_pipe : value -> [`Invalid of string | `Valid]
val unix_socket : value -> [`Invalid of string | `Valid]
val existing_user : value -> [`Invalid of string | `Valid]
val unprivileged_user : value -> [`Invalid of string | `Valid]
val existing_group : value -> [`Invalid of string | `Valid]
val list_of : validation -> value -> [`Invalid of string | `Valid]
